### PR TITLE
Lottie: Add automatic XCode 9.3 fixes.

### PR DESCRIPTION
**Pull request by Shachlan**

### CODE REVIEW

**Comment by barakwei** [comment]
Don't you want to merge from master? it has these `self` fixes.

**Comment by Shachlan** [comment]
XCode would still pester us about the project update.

**Comment by StatusReport** [comment]
Still better to merge from master to avoid future merge conflicts, then you can add your own fixes on top of it.

**Comment by Shachlan** [comment]
Yes, see https://github.com/Lightricks/lottie-ios/pull/3. This branch will be rebased once that is merged.

**Comment by barakwei** [comment]
yalla rebase

**Comment by Shachlan** [comment]
rebased.

**Pull request merged**
