### PR TITLE
[PHOTO-1087] fix buildtime warnings

### PR DESCRIPTION
**Pull request by joemuers**
This PR resolves the compiler warnings (for PhotoLeap, at least) that we are getting from this library.

Changes:
- Adds `GLKit` to the `VALIDATE_WORKSPACE_SKIPPED_SDK_FRAMEWORKS`, this is to suppress the compiler deprecation warning  about using the deprecated GLKit library.

See https://lightricks.atlassian.net/browse/PHOTO-1087 for more details.

### CODE REVIEW

**Comment by barakwei** [comment]
@joemuers another solution would be to not link with GLKit, no?

**Comment by joemuers** [comment]
> @joemuers another solution would be to not link with GLKit, no?

Yes, good idea.

**Comment by joemuers** [comment]
Retest this please.

**Comment by barakwei** [comment]
we don't have to use tests, but why not

**Pull request merged**
